application: prelude-hmpc
version: 3-3
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

default_expiration: "7d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.sublime.*

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/
  static_dir: static

- url: /login
  script: user_admin.app
  secure: always

- url: /login-as
  script: user_admin.app
  secure: always

- url: /register
  script: user_admin.app
  secure: always

- url: /password/.+
  script: user_admin.app
  secure: always

- url: /logout
  script: user_admin.app
  secure: never

- url: /verify/.+
  script: user_admin.app
  secure: never

- url: /reset
  script: user_admin.app
  secure: never

- url: /contact
  script: user_admin.app
  secure: never

- url: /upload
  script: user.app
  secure: never

- url: /user/.*
  script: user.app
  secure: never

- url: /photo/.*
  script: photo.app
  secure: never

- url: /comment/edit/.*
  script: comment.app
  secure: never

- url: /comments
  script: comment.app
  secure: never

- url: /competitions
  script: competition.app
  secure: never

- url: /competition/.*
  script: competition.app
  secure: never

- url: /notes
  script: note.app
  secure: never

- url: /note/new
  script: note.app
  secure: never

- url: /note/edit/.*
  script: note.app
  secure: never

- url: /note/delete/.*
  script: note.app
  secure: never

- url: /_admin
  script: test.app
  secure: never

- url: /help/.*
  script: help.help.app
  secure: never

- url: /about
  script: main.app
  secure: never

- url: .*
  script: main.app
  secure: never

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

- name: PIL
  version: latest
